### ISSUE TITLE
Release recent changes?

### ISSUE THREAD

**Issue by adriendelsalle** [xiaoyeli/superlu_mt#14]
Description
---

Hi!
I would like to know how to map the releases listed at https://portal.nersc.gov/project/sparse/superlu/ and this repo. Maybe it would be possible to tag commits, at least for the latest version?

There are also quite a few commits merged on `master` since v3.1 in 2016.
Is there a chance to cut a release with recent changes?

Thanks!

**Comment by xiaoyeli** [comment]
I just made a new release on github, v4.0.0.  I will update the web portal to sync with this.

**Comment by adriendelsalle** [comment]
awesome! Thanks :)
