### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by rspotnitz** [xiaoyeli/superlu_mt#5]
Trying to run on Windows and when try the test

	pdlinsolx -p [nprocs] < big.rua

get a "HEAP CORRUPTION DETECTED:" message.

Debugging through code, the problem seems to be  in cholnzcnt.c line 243 
should also check that parent does not exceed bounds of colcnt; that is

if ((parent !=0) && (parent < neqns))

**Comment by xiaoyeli** [comment]
Thanks for providing the fix!

The code was originally in Fortran, where 1-based indexing is used, and '0' is used as an added dummy root of the elimination tree (parent[] array).   Now in C, 0-based indexing is used, 'n' is used as an added dummy root.  That line is to check this dummy root.

**Comment by xiaoyeli** [comment]
I committed the fix.

**Comment by rspotnitz** [comment]
Thanks for your explanation.
Should the 0 value be allowed?
Should the check be this?
if ((parent >=0) && (parent < neqns))

**Comment by xiaoyeli** [comment]
that's probably more correct.  But the first condition can be safely removed.
If etree calculation has error (e.g., parent < 0), it's better caught upstream, not at this point.
